"use client";

import { useRef, useState } from "react";

/**
 * TtsStudio — the client UI for the Fish.audio text-to-speech engine.
 * Posts text to /api/tts; plays the returned MP3 (Fish.audio) or falls back to
 * the browser SpeechSynthesis API when no API key is configured.
 */
const MAX_CHARS = 500;

const SAMPLE =
  "Welcome to Shakya.work. This voice is generated by the Fish.audio API on the free tier.";

export default function TtsStudio() {
  const [text, setText] = useState(SAMPLE);
  const [voiceId, setVoiceId] = useState("");
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [info, setInfo] = useState("");
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [engine, setEngine] = useState("");
  const audioRef = useRef<HTMLAudioElement | null>(null);

  function speakBrowser(t: string) {
    if (typeof window === "undefined" || !("speechSynthesis" in window)) return;
    const u = new SpeechSynthesisUtterance(t);
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(u);
  }

  async function generate() {
    const t = text.trim();
    if (!t || busy) return;
    if (t.length > MAX_CHARS) {
      setError(`Free-tier limit is ${MAX_CHARS} characters (you have ${t.length}).`);
      return;
    }
    setBusy(true);
    setError("");
    setInfo("");
    setAudioUrl(null);
    setEngine("");
    try {
      const res = await fetch("/api/tts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: t, voiceId: voiceId.trim() }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Something went wrong.");
        return;
      }
      setEngine(data.engine ?? "");
      if (data.audio) {
        setAudioUrl(data.audio as string);
        if (audioRef.current) {
          audioRef.current.src = data.audio as string;
          audioRef.current.play().catch(() => {});
        }
      } else {
        speakBrowser(t);
        if (data.message) setInfo(data.message);
      }
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="rounded-2xl border border-line bg-surface p-5 sm:p-6">
      <div className="mb-3 flex items-center justify-between">
        <span className="text-[11px] font-medium uppercase tracking-wider text-muted">
          Free tier · {MAX_CHARS} char limit
        </span>
        <span className="text-[11px] text-muted">Powered by Fish.audio</span>
      </div>

      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        maxLength={MAX_CHARS}
        rows={5}
        placeholder="Type the text you want spoken…"
        className="w-full resize-none rounded-lg border border-line bg-paper p-3 text-sm text-ink outline-none focus:border-[#7c3aed]"
      />

      <div className="mt-2 flex items-center justify-between text-[12px] text-muted">
        <button
          type="button"
          onClick={() => setShowAdvanced((v) => !v)}
          className="underline-offset-2 hover:underline"
        >
          {showAdvanced ? "Hide voice ID" : "Advanced: voice ID"}
        </button>
        <span className={text.length > MAX_CHARS ? "text-red-500" : ""}>
          {text.length} / {MAX_CHARS}
        </span>
      </div>

      {showAdvanced && (
        <input
          value={voiceId}
          onChange={(e) => setVoiceId(e.target.value)}
          placeholder="Fish.audio reference_id (optional)"
          className="mt-2 w-full rounded-lg border border-line bg-paper px-3 py-2 text-sm text-ink outline-none focus:border-[#7c3aed]"
        />
      )}

      <button
        onClick={generate}
        disabled={busy || !text.trim()}
        className="mt-4 w-full rounded-lg bg-[#7c3aed] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#6d28d9] disabled:cursor-not-allowed disabled:opacity-50"
      >
        {busy ? "Generating…" : "Generate speech"}
      </button>

      {engine === "fish-audio" && (
        <p className="mt-3 text-[12px] text-[#1a7f43]">🔊 Generated with Fish.audio</p>
      )}
      {info && <p className="mt-3 text-[12px] text-muted">{info}</p>}
      {error && <p className="mt-3 text-[12px] text-red-500">{error}</p>}

      {audioUrl && (
        <div className="mt-4 rounded-lg border border-line bg-paper p-3">
          <audio ref={audioRef} controls src={audioUrl} className="w-full" />
          <a
            href={audioUrl}
            download="tts-output.mp3"
            className="mt-2 inline-block text-[12px] text-[#7c3aed] hover:underline"
          >
            Download MP3 ↓
          </a>
        </div>
      )}
    </div>
  );
}
